version: "3.7"

networks:
    backend:
    pg-backend:

services:
    nginx:
        build:
            context: ./nginx
        restart: always 
        networks:
            - backend
        ports:
            - 0.0.0.0:80:80
        depends_on:
            - restful-server
    postgres:
        image: docker.pkg.github.com/gamelab-hrm/postgres/postgres:0.0.1
        expose:
            - 5432 
        ports:
            - 127.0.0.1:5432:5432 
        networks:
            - pg-backend 
        volumes:
            - postgres-data:/var/lib/postgresql/data
    flyway:
        image: flyway-migration
        restart: on-failure
        networks:
            - pg-backend
            - backend
        depends_on:
            - postgres 

    restful-server:
        image: restful
        restart: always
        user: ${CURRENT_UID}
        ports:
            - 0.0.0.0:8080:8080
        volumes:
            - /home/toby/Desktop/mount:/code/data
        networks:
            - backend
        depends_on:
            - postgres
volumes:
    postgres-data:

